---
- name: Update Nginx default configuration to use port 13371
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: '^(\s*listen\s*)80;'
    line: '    listen 13371;'

- name: Enable the site after port change
  become: yes
  command: ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
  args:
    creates: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

- name: Create directory for Caddyfile
  ansible.builtin.file:
    path: "/etc/caddy/"
    state: directory
    mode: '0755'
    owner: caddy
    group: caddy

- name: Create Caddyfile template
  template:
    src: templates/Caddyfile.j2
    dest: /etc/caddy/Caddyfile

- name: Download Caddy binary
  ansible.builtin.get_url:
    url: https://caddyserver.com/api/download?os=linux&arch=amd64
    dest: /usr/local/bin/caddy
    mode: '0755'

- name: Start Caddy in the background
  ansible.builtin.command: /usr/local/bin/caddy run --config /etc/caddy/Caddyfile
  async: 3600
  poll: 0
  become: yes